name: volunteer-points-log-ci

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        echo -e "\e[32m$i"'Running tests for client'
        cd client
        npm ci
        npm run test --if-present
        cd ..
        echo -e "\e[32m$i"'Running tests for server'
        npm ci
        # npm test --if-present
        echo -e "\e[32m$i"'Building client and server'
        npm run build --if-present
      env:
        CI: true
